name: run my vanilla Cypress tests
on: 
  schedule:
    - cron: '0 1-23 * * *'
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome