name: run my vanilla Cypress tests
on: 
  schedule:
    - cron: '0 1-23 * * *'
    - cron: '0 0 * * *'
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - main

jobs:
  checkout-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome

      # - name: Uploading artefacts
      #   uses: actions/upload-artifacts@v2
      #   if: always()
      #   with:
      #     name: cypress-execution-report
      #     path: cypress/reports/html
      #     retention-days: 30

      # - name: Slack Notification
      #   uses: rtCamp/action-slack-notify@v2
      #   env: 
      #     SLACK_WEBHOOK: ${{secrets.SLACK_WEBHOOK}}
      #     SLACK_USERNAME: obamgbopa
      #     SLACK_TITLE: Regression Test
      #     SLACK_MESSAGE:  "New changes :rocket:"
      #     SLACK_COLOR: ${{job.status}}