name: Pull Request

on: 
  schedule:
    - cron: '0 1-23 * * *'
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      # - name: Lint
      #   run: |
      #     yarn run lint:fix
      #     yarn run lint:check

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }} 
      - name: Build, run test and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/autochek:latest

      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v5
        timeout-minutes: 10
        with:
          browser: chrome
        

              


